service: blops-server

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - '*'

functions:
  graphql:
    warmup: true
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  serverless-offline:
    port: 8080

plugins:
  - serverless-offline
  - serverless-plugin-warmup
