service: blops-server

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
