service: python-lambdas

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${opt:stage} }
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-04c1f7c6dc6b2be33
    subnetIds:
      - subnet-12305468
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:

  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  create_user:
    handler: handler.create_user
    events:
      - http:
          path: /create_user
          method: post
          request:
            template:
              application/json: '{ "httpMethod" : "$context.httpMethod" }'

  login_user:
    handler: handler.login
    events:
      - http:
          path: /login
          method: post
          request:
            template:
              application/json: '{ "httpMethod" : "$context.httpMethod" }'

  test_event:
    handler: handler.test_event
    events:
      - http:
          path: /test_event
          method: post
