service: python-lambdas


# Determines where to deploy, what stage, what VPC, etc.
# This applies to all lambdas (functions).
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${opt:stage} }
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-04c1f7c6dc6b2be33
    subnetIds:
      - subnet-12305468


# Plugins to enhance the application
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup

# Specifies custom container
custom:
  pythonRequirements:
    dockerizePip: non-linux


# Excludes files that should not be packaged
package:
  exclude:
    - requirements.txt
    - input/**
    - tester.py
    - update_schema.py
    - test/**
    - '**/__pycache__/**'


# All lambdas (functions) to package.
functions:

  # Creates a new user
  user_create:
    warmup: true
    handler: handler.user_create

  # Logs in an existing user
  user_login:
    warmup: true
    handler: handler.user_login

  # Logs out an existing user
  user_logout:
    warmup: true
    handler: handler.user_logout

  # Updates an existing user
  user_update:
    warmup: true
    handler: handler.user_update

  # Gets application role info for all users
  user_access:
    warmup: true
    handler: handler.user_access

  # Gets a user with a session token
  user_get:
    warmup: true
    handler: handler.user_get

  # Endpoint for udf_story_air
  udf_story_air:
    warmup: true
    handler: handler.udf_story_air

  # Endpoint for udf_story_air_airlines
  udf_story_air_airlines:
    warmup: true
    handler: handler.udf_story_air_airlines

  # Endpoint for udf_story_air_cabins
  udf_story_air_cabins:
    warmup: true
    handler: handler.udf_story_air_cabins

  # Endpoint for udf_story_air_routes
  udf_story_air_routes:
    warmup: true
    handler: handler.udf_story_air_routes

  # Endpoint for udf_story_air_traffic
  udf_story_air_traffic:
    warmup: true
    handler: handler.udf_story_air_traffic

  # Endpoint for udf_story_hotel
  udf_story_hotel:
    warmup: true
    handler: handler.udf_story_hotel

  # Endpoint for udf_story_hotel_1
  udf_story_hotel_1:
    warmup: true
    handler: handler.udf_story_hotel_1

  # Endpoint for udf_story_hotel_2
  udf_story_hotel_2:
    warmup: true
    handler: handler.udf_story_hotel_2

  # Endpoint for udf_story_hotel_3
  udf_story_hotel_3:
    warmup: true
    handler: handler.udf_story_hotel_3

  # Endpoint for udf_story_hotel_4
  udf_story_hotel_4:
    warmup: true
    handler: handler.udf_story_hotel_4
