service: python-lambdas

provider:
  name: aws
  runtime: python3.7

functions:
  
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  create_user:
    handler: handler.create_user
    events:
      - http:
          path: /
          method: get
