service: python-lambdas

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):dev}

functions:
  hello:
    handler: src.handler.hello
    events:
      - http:
          path: /
          method: get

  create_user:
    handler: src.handler.create_user
    events:
      - http:
          path: /create_user
          method: get
