service: graphene-lambda

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'test'}
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "*"

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: app.app
    packRequirements: false

# Lambda functions.
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
