service: graphene-lambda 

#
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'test'}
  region: us-east-2

#
plugins:
  - serverless-python-requirements
  - serverless-wsgi

# 
custom:
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: app.app
    packRequirements: false

# Lambda functions.
functions:
  #hello:
  #  handler: handler.hello
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http: POST /graphql
